<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="pk_appium.WindowsOS_App_Testing" tests="6" time="0.010" ignored="0" failures="0" timestamp="28 Aug 2020 17:38:55 GMT" skipped="5" hostname="HIBACL131408" errors="1">
  <testcase name="Addition" time="0.003" classname="pk_appium.WindowsOS_App_Testing">
    <skipped/>
  </testcase> <!-- Addition -->
  <testcase name="Subtraction" time="0.002" classname="pk_appium.WindowsOS_App_Testing">
    <skipped/>
  </testcase> <!-- Subtraction -->
  <testcase name="Combination" time="0.001" classname="pk_appium.WindowsOS_App_Testing">
    <skipped/>
  </testcase> <!-- Combination -->
  <testcase name="Clear" time="0.000" classname="pk_appium.WindowsOS_App_Testing">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pk_appium.WindowsOS_App_Testing.Clear(WindowsOS_App_Testing.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.TestRunner.beforeRun(TestRunner.java:634)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- Clear -->
  <testcase name="Multiplication" time="0.002" classname="pk_appium.WindowsOS_App_Testing">
    <skipped/>
  </testcase> <!-- Multiplication -->
  <testcase name="Division" time="0.002" classname="pk_appium.WindowsOS_App_Testing">
    <skipped/>
  </testcase> <!-- Division -->
</testsuite> <!-- pk_appium.WindowsOS_App_Testing -->
